import type { Metadata } from "next";
import { Manrope } from "next/font/google";  // Importing Manrope font from Google Fonts
import "./globals.css"; // Importing global styles

const manrope = Manrope({
  variable: "--font-manrope",  // You can change this variable name if needed
  subsets: ["latin"],         // Add other subsets as needed
  weight: ["400", "600", "700"], // Normal, semi-bold, and bold weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>


        {/* Logo Section */}
        <div className="relative z-20 flex -mb-15">
          <div className="logo-container">
            <img
              src="/images/eleksyon-logo-new.png"
              alt="Eleksyon Logo"
              className="eleksyon-logo"
            />
          </div>
        </div>

        {/* Header Section*/}
        <div className="header-container">

          {/* Main Header */}
          <header className="main-header relative z-10 flex items-center px-4 py-2 bg-blue-700">
            
            {/* Main Navigation Header */}
            <nav className="flex flex-1 justify-center items-center gap-8 text-white font-semibold">
              <a href="/">Transmission</a>
              <a href="/analytics">Analytics</a>
              <a href="/voters-profile">Voter's Profile</a>
            </nav>

          </header>
      

        {/* Sub Header */}
        <header className="sub-header gap-8 text-white font-semibold">
          <a href="/senate">SENATE</a>
          <a href="/party-list">PARTY-LIST</a>
          <a href="/provincial">PROVINCIAL</a>
          <a href="/city">CITY</a>
        </header>
      </div>
        
      <main className="content-container">
        {children}
    </main>
      </body>
    </html>
  );
}
