import type { Metadata } from "next";
import { Manrope } from "next/font/google";  // Importing Manrope font from Google Fonts
import "./globals.css"; // Importing global styles

const manrope = Manrope({
  variable: "--font-manrope",  // You can change this variable name if needed
  subsets: ["latin"],         // Add other subsets as needed
  weight: ["400", "600", "700"], // Normal, semi-bold, and bold weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        {/* Main Header */}
        <header className="main-header ">
          <div className="header-content">Header</div>
          <img
              src="/images/eleksyon-logo.png"  
              alt="Eleksyon Logo" 
              className="w-[243px] h-[152.9px] transform -translate-x-3 -translate-y-27"
            />
        </header>

        {/* Sub Header */}
        <header className="sub-header">
          <div className="header-content">SUB HEADER </div>
        </header>

        {/* Main Content */}
        {children}
      </body>
    </html>
  );
}
